import Head from "next/head";
import { useCallback, useEffect, useState } from "react";
import { Footer } from "src/Components/Footer";
import { Header } from "src/Components/Header";
import styles from "src/styles/Home.module.css";
import useSWR from "swr";

const Home = (props) => {
	const [posts, setPosts] = useState([]);
	const fetcher = (...args) => fetch(...args).then((res) => res.json());
	const { data, error } = useSWR(
		"https://jsonplaceholder.typicode.com/posts",
		fetcher
	);

	if (error) return <div>データがありません</div>;
	if (!data) return <div>Loading...</div>;
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Header />

			<div>
				<ol>
					{data.map((item) => {
						return <li key={item.id}>{item.title}</li>;
					})}
				</ol>
			</div>
			<Footer />
		</div>
	);
};
export default Home;
